In [1]:
from tensorly.tenalg.proximal import active_set_nnls, hals_nnls
from fista_edit import *
import numpy as np
import tensorly as tl
from tensorly.decomposition._cp import initialize_cp
from tensorly.metrics.regression import RMSE

In [2]:
array=np.random.randint(8, size=(10,10))
a=tl.tensor(array,dtype=float)
b=tl.tensor(np.random.randint(8, size=(10,1)))

atb = tl.dot(tl.transpose(a),b)
ata = tl.dot(tl.transpose(a),a)

print(a)
print(b)


[[6. 1. 2. 3. 5. 7. 3. 6. 1. 6.]
 [1. 0. 2. 2. 1. 1. 3. 7. 1. 6.]
 [2. 0. 4. 2. 6. 6. 2. 0. 3. 4.]
 [7. 2. 0. 4. 0. 6. 7. 3. 7. 7.]
 [6. 2. 7. 5. 6. 7. 3. 5. 0. 1.]
 [1. 1. 7. 2. 5. 1. 1. 6. 4. 5.]
 [1. 2. 1. 5. 6. 4. 4. 2. 7. 4.]
 [3. 7. 4. 5. 7. 0. 3. 4. 1. 0.]
 [0. 3. 1. 3. 2. 0. 3. 4. 7. 2.]
 [7. 5. 4. 7. 7. 6. 2. 5. 1. 7.]]
[[5]
 [3]
 [3]
 [4]
 [0]
 [4]
 [5]
 [2]
 [7]
 [0]]


# Tl.solve

In [3]:
x = tl.solve(a,b)
print(tl.dot(a,x))

[[ 5.00000000e+00]
 [ 3.00000000e+00]
 [ 3.00000000e+00]
 [ 4.00000000e+00]
 [ 3.60822483e-16]
 [ 4.00000000e+00]
 [ 5.00000000e+00]
 [ 2.00000000e+00]
 [ 7.00000000e+00]
 [-8.88178420e-16]]


# Fista

In [45]:
x = fista(atb, ata,lr=0.001, n_iter_max=1000,  tol=10e-8)
print(tl.dot(a,x))

[[2.35565352]
 [2.63822483]
 [1.98067712]
 [5.46929385]
 [1.41285651]
 [4.33633064]
 [5.18672255]
 [1.79051092]
 [5.75186516]
 [2.07308222]]


# Active set

In [5]:
x = active_set_nnls(tl.base.tensor_to_vec(atb), ata)
x=tl.reshape(x,tl.shape(atb))
print(tl.dot(a,x))

[[2.35565334]
 [2.6382246 ]
 [1.98067725]
 [5.46929405]
 [1.41285632]
 [4.33633059]
 [5.18672279]
 [1.79051081]
 [5.75186531]
 [2.07308207]]


# HALS

In [6]:
xinit=tl.zeros(tl.shape(atb))
x = hals_nnls(atb, ata, V=xinit)[0]
print(tl.dot(a,x))

[[2.73062831]
 [2.42050683]
 [2.72314496]
 [5.97538906]
 [2.2795248 ]
 [3.44454677]
 [5.47291901]
 [2.71851998]
 [4.9361055 ]
 [2.49182795]]
