In [1]:
from tensorly.tenalg.proximal import active_set_nnls, hals_nnls
from fista_edit import *
import numpy as np
import tensorly as tl
from tensorly.decomposition._cp import initialize_cp
from tensorly.metrics.regression import RMSE

In [2]:
array=np.random.randint(8, size=(10,10))
a=tl.tensor(array,dtype=float)
b=tl.tensor(np.random.randint(8, size=(10,1)))

atb = tl.dot(tl.transpose(a),b)
ata = tl.dot(tl.transpose(a),a)

print(a)
print(b)


[[0. 3. 0. 5. 6. 2. 1. 1. 5. 2.]
 [3. 3. 7. 6. 2. 6. 0. 4. 6. 2.]
 [0. 7. 0. 0. 0. 6. 3. 5. 2. 6.]
 [5. 1. 5. 7. 6. 3. 2. 7. 4. 1.]
 [2. 6. 3. 0. 2. 3. 6. 7. 5. 3.]
 [2. 2. 7. 6. 2. 2. 0. 2. 6. 7.]
 [0. 7. 2. 7. 7. 7. 7. 6. 1. 0.]
 [1. 7. 1. 5. 2. 4. 7. 2. 1. 6.]
 [2. 5. 0. 1. 4. 5. 0. 3. 0. 5.]
 [0. 4. 1. 3. 4. 1. 6. 1. 3. 0.]]
[[1]
 [6]
 [5]
 [4]
 [4]
 [7]
 [3]
 [4]
 [4]
 [7]]


# Tl.solve

In [3]:
x = tl.solve(a,b)
print(tl.dot(a,x))

[[1.]
 [6.]
 [5.]
 [4.]
 [4.]
 [7.]
 [3.]
 [4.]
 [4.]
 [7.]]


# Fista

In [4]:
x = fista(atb, ata,lr=0.001, n_iter_max=1000,  tol=10e-8)
print(tl.dot(a,x))

[[2.43961375]
 [5.74485499]
 [4.1863105 ]
 [3.99172202]
 [5.53569901]
 [6.6805027 ]
 [4.2008232 ]
 [5.06722536]
 [2.74950168]
 [2.98791273]]


# Active set

In [5]:
x = active_set_nnls(tl.base.tensor_to_vec(atb), ata)
x=tl.reshape(x,tl.shape(atb))
print(tl.dot(a,x))

[[2.43961256]
 [5.744855  ]
 [4.18631007]
 [3.99172251]
 [5.53569843]
 [6.68050304]
 [4.20082389]
 [5.06722578]
 [2.74950214]
 [2.98791231]]


# HALS

In [6]:
xinit=tl.zeros(tl.shape(atb))
x = hals_nnls(atb, ata, V=xinit)[0]
print(tl.dot(a,x))

[[2.08662331]
 [6.20975577]
 [4.24870621]
 [5.65047253]
 [6.06227086]
 [4.97437373]
 [4.75240479]
 [5.14471297]
 [4.27776511]
 [2.8305381 ]]
