In [1]:
from tensorly.tenalg.proximal import active_set_nnls, hals_nnls, fista
import numpy as np
import tensorly as tl
from tensorly.decomposition._cp import initialize_cp
from tensorly.metrics.regression import RMSE

In [2]:
array=np.random.randint(8, size=(20,20))
a=tl.tensor(array,dtype=float)
b=tl.tensor(np.random.randint(8, size=(20,1)))

atb = tl.dot(tl.transpose(a),b)
ata = tl.dot(tl.transpose(a),a)

print(a)
print(b)


[[4. 3. 4. 0. 6. 7. 6. 4. 4. 1. 3. 5. 3. 4. 7. 2. 7. 5. 1. 0.]
 [4. 1. 6. 6. 7. 5. 5. 6. 2. 0. 0. 1. 4. 1. 5. 6. 1. 3. 5. 1.]
 [3. 1. 6. 6. 4. 6. 5. 7. 5. 7. 4. 4. 1. 7. 0. 2. 5. 0. 7. 2.]
 [0. 4. 1. 6. 7. 1. 2. 3. 3. 5. 5. 7. 7. 4. 1. 1. 6. 0. 4. 6.]
 [5. 0. 6. 4. 0. 1. 7. 3. 3. 7. 4. 4. 4. 3. 6. 2. 7. 1. 7. 2.]
 [1. 1. 2. 4. 5. 6. 2. 1. 0. 5. 4. 5. 6. 3. 0. 0. 5. 2. 4. 4.]
 [1. 0. 1. 3. 6. 1. 1. 1. 0. 3. 5. 2. 2. 0. 1. 4. 7. 3. 2. 4.]
 [7. 3. 5. 2. 3. 5. 6. 4. 7. 7. 4. 7. 3. 6. 5. 5. 3. 5. 1. 4.]
 [0. 0. 6. 5. 1. 0. 4. 5. 0. 0. 0. 1. 0. 4. 4. 5. 7. 6. 4. 4.]
 [5. 7. 2. 3. 3. 5. 7. 0. 2. 6. 7. 1. 7. 7. 1. 7. 4. 1. 7. 1.]
 [0. 5. 2. 2. 6. 1. 6. 3. 6. 3. 1. 3. 2. 1. 0. 4. 5. 1. 6. 6.]
 [6. 7. 3. 4. 6. 1. 6. 1. 3. 4. 5. 6. 1. 6. 1. 1. 7. 7. 1. 7.]
 [4. 7. 5. 2. 3. 7. 0. 2. 1. 4. 4. 0. 2. 6. 2. 3. 6. 4. 6. 7.]
 [0. 3. 7. 6. 7. 2. 7. 0. 2. 4. 5. 5. 4. 3. 1. 3. 3. 3. 7. 1.]
 [5. 0. 5. 2. 5. 2. 5. 7. 4. 4. 0. 5. 0. 4. 4. 2. 2. 6. 4. 4.]
 [0. 4. 0. 0. 2. 1. 4. 0. 1. 4. 4. 7. 4. 7. 4. 4. 3. 5.

# Tl.solve

In [3]:
x = tl.solve(a,b)
print(tl.dot(a,x))

[[ 5.00000000e+00]
 [ 5.00000000e+00]
 [ 7.00000000e+00]
 [ 2.00000000e+00]
 [ 5.00000000e+00]
 [ 6.00000000e+00]
 [ 1.77635684e-15]
 [ 5.00000000e+00]
 [ 7.00000000e+00]
 [ 5.00000000e+00]
 [ 3.00000000e+00]
 [ 3.00000000e+00]
 [ 2.00000000e+00]
 [ 5.00000000e+00]
 [ 4.00000000e+00]
 [-1.77635684e-15]
 [ 5.00000000e+00]
 [ 1.00000000e+00]
 [ 1.00000000e+00]
 [ 3.00000000e+00]]


# Fista

In [4]:
x = fista(atb, ata,lr=0.0001, tol=10e-8)
print(tl.dot(a,x))

[[4.98581796]
 [5.11705004]
 [6.46735995]
 [2.88813774]
 [4.85845064]
 [3.35030801]
 [1.84399303]
 [5.10283276]
 [3.99093513]
 [3.89963766]
 [3.35177961]
 [3.40346299]
 [3.69601331]
 [4.07827292]
 [4.6899112 ]
 [1.62890103]
 [3.43226608]
 [3.64778785]
 [3.05097097]
 [3.25698771]]


# Active set

In [5]:
x = active_set_nnls(tl.base.tensor_to_vec(atb), ata)
x=tl.reshape(x,tl.shape(atb))
print(tl.dot(a,x))

[[4.99138904]
 [5.08356897]
 [6.4431456 ]
 [2.85647383]
 [4.88905662]
 [3.32414584]
 [1.825592  ]
 [5.12620704]
 [3.97142102]
 [3.92443988]
 [3.3719856 ]
 [3.41840611]
 [3.66599174]
 [4.0985003 ]
 [4.70055432]
 [1.66011731]
 [3.44425115]
 [3.64681752]
 [3.0326106 ]
 [3.263909  ]]


# HALS

In [6]:
xinit=tl.zeros(tl.shape(atb))
x = hals_nnls(atb, ata, V=xinit, exact=True)[0]
print(tl.dot(a,x))

[[4.99138904]
 [5.08356897]
 [6.4431456 ]
 [2.85647383]
 [4.88905662]
 [3.32414584]
 [1.825592  ]
 [5.12620704]
 [3.97142102]
 [3.92443988]
 [3.3719856 ]
 [3.41840611]
 [3.66599174]
 [4.0985003 ]
 [4.70055432]
 [1.66011731]
 [3.44425115]
 [3.64681752]
 [3.0326106 ]
 [3.263909  ]]
