In [1]:
from tensorly.tenalg.proximal import active_set_nnls, fista
import numpy as np
import tensorly as tl
from tensorly.decomposition._cp import initialize_cp
from tensorly.metrics.regression import RMSE

In [2]:
array=np.random.randint(8, size=(3,3,4))
a=tl.tensor(array,dtype=float)
b=[]
b.append(tl.tensor(np.random.randint(8, size=(3,3)),dtype=float))
b.append(tl.tensor(np.random.randint(8, size=(3,3)),dtype=float))
b.append(tl.tensor(np.random.randint(8, size=(4,4)),dtype=float))

b_kr = tl.tenalg.kronecker(b)
print(tl.shape(a))
print(tl.shape(b_kr))
print(a)

(3, 3, 4)
(36, 36)
[[[4. 7. 0. 2.]
  [1. 6. 0. 5.]
  [1. 3. 7. 4.]]

 [[2. 1. 2. 1.]
  [2. 4. 0. 3.]
  [0. 2. 1. 6.]]

 [[3. 0. 5. 3.]
  [3. 7. 2. 7.]
  [7. 2. 3. 6.]]]


# Fista

In [13]:
x_fista = fista(a, b)
print(tl.shape(x_fista))
print(tl.tenalg.multi_mode_dot(x_fista, b))

(3, 3, 4)
[[[-3.62691679e+153 -4.56965329e+153 -2.52705755e+153 -7.08361728e+153]
  [-7.21455290e+153 -9.15240014e+153 -5.18505072e+153 -1.34601822e+154]
  [ 2.09496999e+152 -2.77583524e+153 -1.27007556e+153 -2.36993480e+153]]

 [[-2.76274167e+153 -3.33885842e+153 -2.18662493e+153 -3.70547817e+153]
  [-4.81843097e+153 -5.83972884e+153 -3.82332023e+153 -6.46821984e+153]
  [-1.66288243e+153 -2.42230905e+153 -1.55813393e+153 -2.36993480e+153]]

 [[-1.76763093e+153 -2.29137343e+153 -1.08676568e+153 -4.07209792e+153]
  [-3.99353654e+153 -5.17195716e+153 -2.67108674e+153 -8.22275721e+153]
  [ 7.85613746e+152 -1.23079487e+153 -3.53526186e+152 -9.29642933e+152]]]


# Active set

In [8]:
x = active_set_nnls(b_kr, tl.base.tensor_to_vec(a))
x_active = tl.reshape(x, tl.shape(a))
print(tl.shape(x_active))
print(tl.reshape(tl.dot(b_kr, x), tl.shape(a)))

(3, 3, 4)
[[[18.66666667 18.66666667  9.33333333 56.        ]
  [32.66666667 32.66666667 16.33333333 98.        ]
  [14.         14.          7.         42.        ]]

 [[ 2.66666667  2.66666667  1.33333333  8.        ]
  [ 4.66666667  4.66666667  2.33333333 14.        ]
  [ 2.          2.          1.          6.        ]]

 [[13.33333333 13.33333333  6.66666667 40.        ]
  [23.33333333 23.33333333 11.66666667 70.        ]
  [10.         10.          5.         30.        ]]]


# Tl.solve

In [9]:
x = tl.solve(b_kr, tl.base.tensor_to_vec(a))
x_solve = tl.reshape(x, tl.shape(a))
print(tl.shape(x_solve))
print(tl.reshape(tl.dot(b_kr,x), tl.shape(a)))

(3, 3, 4)
[[[ 4.00000000e+00  7.00000000e+00  1.33226763e-14  2.00000000e+00]
  [ 1.00000000e+00  6.00000000e+00  1.36002321e-15  5.00000000e+00]
  [ 1.00000000e+00  3.00000000e+00  7.00000000e+00  4.00000000e+00]]

 [[ 2.00000000e+00  1.00000000e+00  2.00000000e+00  1.00000000e+00]
  [ 2.00000000e+00  4.00000000e+00  4.57966998e-16  3.00000000e+00]
  [-1.60982339e-15  2.00000000e+00  1.00000000e+00  6.00000000e+00]]

 [[ 3.00000000e+00  2.09277040e-14  5.00000000e+00  3.00000000e+00]
  [ 3.00000000e+00  7.00000000e+00  2.00000000e+00  7.00000000e+00]
  [ 7.00000000e+00  2.00000000e+00  3.00000000e+00  6.00000000e+00]]]
